### PR TITLE
Fix for #367

### PR DESCRIPTION
**Pull request by lucteo**
Rename the naming of sections in the following way:
- "execution" -> "exec"
- "schedulers" -> "sched"
- "receivers" -> "recv"
- "senders" -> "snd"
- "queries" -> "qr"
- "adaptors" -> "adapt"
- "snd_rec_utils" -> "utils"
- "contexts" -> "ctx"

Similar to sender factories, drop the "adaptor" and "consumer" from
sections corresponding to individual senders.

### CODE REVIEW

**Comment by lucteo** [comment]
For reference, here is the TOC for the sections with labels:
```
7 General utilities library                       [utilities]
7.1 Function objects                              [function.objects]
7.1.1 Header <functional> synopsis                [functional.syn]
7.1.2 execution::tag_invoke                       [func.tag_invoke]
8 Thread support library                          [thread]
8.1 Stop tokens                                   [thread.stoptoken]
8.1.1 Header <stop_token> synopsis                [thread.stoptoken.syn]
8.1.2 Stop token concepts                         [thread.stoptoken.concepts]
9 Execution control library                       [exec]
9.1 Header <execution> synopsis                   [exec.syn]
9.2 Helper concepts                               [exec.helpers]
9.3 General queries                               [exec.qr] #
9.3.1 execution::get_scheduler                    [exec.qr.get_scheduler]
9.3.2 execution::get_delegee_scheduler            [exec.qr.get_delegee_scheduler]
9.3.3 execution::get_allocator                    [exec.qr.get_allocator]
9.3.4 execution::get_stop_token                   [exec.qr.get_stop_token]
9.4 Schedulers                                    [exec.sched]
9.4.1 Scheduler queries                           [exec.sched.qr]
9.4.1.1 execution::forwarding_scheduler_query     [exec.sched.qr.forwarding_scheduler_query]
9.4.1.2 execution::get_forward_progress_guarantee [exec.sched.qr.get_forward_progress_guarantee]
9.4.1.3 this_thread::execute_may_block_caller     [exec.sched.qr.execute_may_block_caller]
9.5 Receivers                                     [exec.recv]
9.5.1 execution::set_value                        [exec.recv.set_value]
9.5.2 execution::set_error                        [exec.recv.set_error]
9.5.3 execution::set_done                         [exec.recv.set_done]
9.5.4 Receiver queries                            [exec.recv.qr]
9.5.4.1 execution::forwarding_receiver_query      [exec.recv.qr.forwarding_receiver_query]
9.6 Operation states                              [exec.op_state]
9.6.1 execution::start                            [exec.op_state.start]
9.7 Senders                                       [exec.snd]
9.7.1 Sender traits                               [exec.snd.traits]
9.7.2 execution::connect                          [exec.snd.connect]
9.7.3 Sender queries                              [exec.snd.qr]
9.7.3.1 execution::forwarding_sender_query        [exec.snd.qr.forwarding_sender_query]
9.7.3.2 execution::get_completion_scheduler       [exec.snd.qr.get_completion_scheduler]
9.7.4 Sender factories                            [exec.snd.factories]
9.7.4.1 General                                   [exec.snd.factories.general]
9.7.4.2 execution::schedule                       [exec.snd.schedule]
9.7.4.3 execution::just                           [exec.snd.just]
9.7.4.4 execution::transfer_just                  [exec.snd.transfer_just]
9.7.4.5 execution::just_error                     [exec.snd.just_error]
9.7.4.6 execution::just_done                      [exec.snd.just_done]
9.7.5 Sender adaptors                             [exec.snd.adapt]
9.7.5.1 General                                   [exec.snd.adapt.general]
9.7.5.2 Sender adaptor closure objects            [exec.snd.adapt.objects]
9.7.5.3 execution::on                             [exec.snd.on]
9.7.5.4 execution::transfer                       [exec.snd.transfer]
9.7.5.5 execution::schedule_from                  [exec.snd.schedule_from]
9.7.5.6 execution::then                           [exec.snd.then]
9.7.5.7 execution::upon_error                     [exec.snd.upon_error]
9.7.5.8 execution::upon_done                      [exec.snd.upon_done]
9.7.5.9 execution::let_value                      [exec.snd.let_value]
9.7.5.10 execution::let_error                     [exec.snd.let_error]
9.7.5.11 execution::let_done                      [exec.snd.let_done]
9.7.5.12 execution::bulk                          [exec.snd.bulk]
9.7.5.13 execution::split                         [exec.snd.split]
9.7.5.14 execution::when_all                      [exec.snd.when_all]
9.7.5.15 execution::transfer_when_all             [exec.snd.transfer_when_all]
9.7.5.16 execution::into_variant                  [exec.snd.into_variant]
9.7.5.17 execution::done_as_optional              [exec.snd.done_as_optional]
9.7.5.18 execution::done_as_error                 [exec.snd.done_as_error]
9.7.5.19 execution::ensure_started                [exec.snd.ensure_started]
9.7.6 Sender consumers                            [exec.snd.consumers]
9.7.6.1 execution::start_detached                 [exec.snd.start_detached]
9.7.6.2 this_thread::sync_wait                    [exec.snd.sync_wait]
9.8 execution::execute                            [exec.execute]
9.9 Sender/receiver utilities                     [exec.utils]
9.9.1 execution::receiver_adaptor                 [exec.utils.rcvr_adptr]
9.9.1.1 Non-member functions                      [exec.utils.receiver_adaptor.nonmembers]
9.9.2 execution::completion_signatures            [exec.utils.completion_sigs]
9.10 Execution contexts                           [exec.ctx]
9.10.1 run_loop                                   [exec.ctx.run_loop]
9.10.1.1 Associated types                         [exec.ctx.run_loop.types]
9.10.1.2 Constructor and destructor               [exec.ctx.run_loop.ctor]
9.10.1.3 Member functions                         [exec.ctx.run_loop.members]
9.11 Coroutine utilities                          [exec.coro_utils]
9.11.1 execution::as_awaitable                    [exec.coro_utils.as_awaitable]
9.11.2 execution::with_awaitable_senders          [exec.coro_utils.with_awaitable_senders]
```

**Comment by lucteo** [comment]
@ericniebler : this has a lot of changes, and will most-likely conflict with other patches.
I think it's best to review/merge this first

**Comment by miscco** [comment]
I am really not a fan of this. Yeah we can shorten execution to exec or whatever because that is a clear and common name. but `qr` and `snd` are really more obfuscating and not helping

**Comment by ericniebler** [comment]
```
9.9.1 execution::receiver_adaptor                 [exec.utils.rcvr_adptr]
9.9.1.1 Non-member functions                      [exec.utils.receiver_adaptor.nonmembers]
```

Looks inconsistent

**Comment by ericniebler** [comment]
First I would `s/qr\.//g`
Then I would `s/exec.qr/exec.queries/g`
Then I would `s/exec\.(\w+)\.qr\./exec.$1_queries./g`
Then I would `s/exec\.\w+\./exec./g`

Then let's take stock of where we're at.

**Comment by lucteo** [comment]
After the suggested changes, the labels are:
```
# General utilities library                      [utilities]
## Function objects                              [function.objects]
### Header `<functional>` synopsis               [functional.syn]
### `execution::tag_invoke`                      [func.tag_invoke]
# Thread support library                         [thread]
## Stop tokens                                   [thread.stoptoken]
### Header `<stop_token>` synopsis               [thread.stoptoken.syn]
### Stop token concepts                          [thread.stoptoken.concepts]
# Execution control library                      [exec]
## Header `<execution>` synopsis                 [exec.syn]
## Helper concepts                               [exec.helpers]
## General queries                               [exec.queries]
### `execution::get_scheduler`                   [exec.queries.get_scheduler]
### `execution::get_delegee_scheduler`           [exec.queries.get_delegee_scheduler]
### `execution::get_allocator`                   [exec.queries.get_allocator]
### `execution::get_stop_token`                  [exec.queries.get_stop_token]
## Schedulers                                    [exec.sched] 
### Scheduler queries                            [exec.sched_queries]
#### `execution::forwarding_scheduler_query`     [exec.sched_queries.forwarding_scheduler_query]
#### `execution::get_forward_progress_guarantee` [exec.sched_queries.get_forward_progress_guarantee]
#### `this_thread::execute_may_block_caller`     [exec.sched_queries.execute_may_block_caller]
## Receivers                                     [exec.recv]
### `execution::set_value`                       [exec.recv.set_value]
### `execution::set_error`                       [exec.recv.set_error]
### `execution::set_done`                        [exec.recv.set_done]
### Receiver queries                             [exec.recv_queries]
#### `execution::forwarding_receiver_query`      [exec.recv_queries.forwarding_receiver_query]
## Operation states                              [exec.op_state]
### `execution::start`                           [exec.op_state.start]
## Senders                                       [exec.snd]
### Sender traits                                [exec.snd.traits]
### `execution::connect`                         [exec.snd.connect]
### Sender queries                               [exec.snd_queries]
#### `execution::forwarding_sender_query`        [exec.snd_queries.forwarding_sender_query]
#### `execution::get_completion_scheduler`       [exec.snd_queries.get_completion_scheduler]
### Sender factories                             [exec.snd.factories]
#### General                                     [exec.snd.factories.general]
#### `execution::schedule`                       [exec.snd.schedule]
#### `execution::just`                           [exec.snd.just]
#### `execution::transfer_just`                  [exec.snd.transfer_just]
#### `execution::just_error`                     [exec.snd.just_error]
#### `execution::just_done`                      [exec.snd.just_done]
### Sender adaptors                              [exec.snd.adapt]
#### General                                     [exec.snd.adapt.general]
#### Sender adaptor closure objects              [exec.snd.adapt.objects]
#### `execution::on`                             [exec.snd.on]
#### `execution::transfer`                       [exec.snd.transfer]
#### `execution::schedule_from`                  [exec.snd.schedule_from]
#### `execution::then`                           [exec.snd.then]
#### `execution::upon_error`                     [exec.snd.upon_error]
#### `execution::upon_done`                      [exec.snd.upon_done]
#### `execution::let_value`                      [exec.snd.let_value]
#### `execution::let_error`                      [exec.snd.let_error]
#### `execution::let_done`                       [exec.snd.let_done]
#### `execution::bulk`                           [exec.snd.bulk]
#### `execution::split`                          [exec.snd.split]
#### `execution::when_all`                       [exec.snd.when_all]
#### `execution::transfer_when_all`              [exec.snd.transfer_when_all]
#### `execution::into_variant`                   [exec.snd.into_variant]
#### `execution::done_as_optional`               [exec.snd.done_as_optional]
#### `execution::done_as_error`                  [exec.snd.done_as_error]
#### `execution::ensure_started`                 [exec.snd.ensure_started]
### Sender consumers                             [exec.snd.consumers]
#### `execution::start_detached`                 [exec.snd.start_detached]
#### `this_thread::sync_wait`                    [exec.snd.sync_wait]
## `execution::execute`                          [exec.execute]
## Sender/receiver utilities                     [exec.utils]
### `execution::receiver_adaptor`                [exec.utils.rcvr_adptr]
#### Non-member functions                        [exec.utils.rcvr_adptr.nonmembers]
### `execution::completion_signatures`           [exec.utils.completion_sigs]
## Execution contexts                            [exec.ctx]
### `run_loop`                                   [exec.ctx.run_loop]
#### Associated types                            [exec.ctx.run_loop.types]
#### Constructor and destructor                  [exec.ctx.run_loop.ctor]
#### Member functions                            [exec.ctx.run_loop.members]
## Coroutine utilities                           [exec.coro_utils]
### `execution::as_awaitable`                    [exec.coro_utils.as_awaitable]
### `execution::with_awaitable_senders`          [exec.coro_utils.with_awaitable_senders]
```

**Comment by ericniebler** [comment]
This is a big improvement. Let's also do:

`s/snd\.//g`
`s/ctx\.//g`
`s/coro_utils\.//g`

And after that I think we're good.

**Comment by lucteo** [comment]
New labels:
```
# General utilities library                      [utilities]
## Function objects                              [function.objects]
### Header `<functional>` synopsis               [functional.syn]
### `execution::tag_invoke`                      [func.tag_invoke]
# Thread support library                         [thread]
## Stop tokens                                   [thread.stoptoken]
### Header `<stop_token>` synopsis               [thread.stoptoken.syn]
### Stop token concepts                          [thread.stoptoken.concepts]
# Execution control library                      [exec]
## Header `<execution>` synopsis                 [exec.syn]
## Helper concepts                               [exec.helpers]
## General queries                               [exec.queries]
### `execution::get_scheduler`                   [exec.queries.get_scheduler]
### `execution::get_delegee_scheduler`           [exec.queries.get_delegee_scheduler]
### `execution::get_allocator`                   [exec.queries.get_allocator]
### `execution::get_stop_token`                  [exec.queries.get_stop_token]
## Schedulers                                    [exec.sched] 
### Scheduler queries                            [exec.sched_queries]
#### `execution::forwarding_scheduler_query`     [exec.sched_queries.forwarding_scheduler_query]
#### `execution::get_forward_progress_guarantee` [exec.sched_queries.get_forward_progress_guarantee]
#### `this_thread::execute_may_block_caller`     [exec.sched_queries.execute_may_block_caller]
## Receivers                                     [exec.recv]
### `execution::set_value`                       [exec.set_value]
### `execution::set_error`                       [exec.set_error]
### `execution::set_done`                        [exec.set_done]
### Receiver queries                             [exec.recv_queries]
#### `execution::forwarding_receiver_query`      [exec.recv_queries.forwarding_receiver_query]
## Operation states                              [exec.op_state]
### `execution::start`                           [exec.op_state.start]
## Senders                                       [exec.snd]
### Sender traits                                [exec.snd_traits]
### `execution::connect`                         [exec.connect]
### Sender queries                               [exec.snd_queries]
#### `execution::forwarding_sender_query`        [exec.snd_queries.forwarding_sender_query]
#### `execution::get_completion_scheduler`       [exec.snd_queries.get_completion_scheduler]
### Sender factories                             [exec.factories]
#### General                                     [exec.factories.general]
#### `execution::schedule`                       [exec.schedule]
#### `execution::just`                           [exec.just]
#### `execution::transfer_just`                  [exec.transfer_just]
#### `execution::just_error`                     [exec.just_error]
#### `execution::just_done`                      [exec.just_done]
### Sender adaptors                              [exec.adapt]
#### General                                     [exec.adapt.general]
#### Sender adaptor closure objects              [exec.adapt.objects]
#### `execution::on`                             [exec.on]
#### `execution::transfer`                       [exec.transfer]
#### `execution::schedule_from`                  [exec.schedule_from]
#### `execution::then`                           [exec.then]
#### `execution::upon_error`                     [exec.upon_error]
#### `execution::upon_done`                      [exec.upon_done]
#### `execution::let_value`                      [exec.let_value]
#### `execution::let_error`                      [exec.let_error]
#### `execution::let_done`                       [exec.let_done]
#### `execution::bulk`                           [exec.bulk]
#### `execution::split`                          [exec.split]
#### `execution::when_all`                       [exec.when_all]
#### `execution::transfer_when_all`              [exec.transfer_when_all]
#### `execution::into_variant`                   [exec.into_variant]
#### `execution::done_as_optional`               [exec.done_as_optional]
#### `execution::done_as_error`                  [exec.done_as_error]
#### `execution::ensure_started`                 [exec.ensure_started]
### Sender consumers                             [exec.consumers]
#### `execution::start_detached`                 [exec.start_detached]
#### `this_thread::sync_wait`                    [exec.sync_wait]
## `execution::execute`                          [exec.execute]
## Sender/receiver utilities                     [exec.utils]
### `execution::receiver_adaptor`                [exec.utils.rcvr_adptr]
#### Non-member functions                        [exec.utils.rcvr_adptr.nonmembers]
### `execution::completion_signatures`           [exec.utils.completion_sigs]
## Execution contexts                            [exec.ctx]
### `run_loop`                                   [exec.run_loop]
#### Associated types                            [exec.run_loop.types]
#### Constructor and destructor                  [exec.run_loop.ctor]
#### Member functions                            [exec.run_loop.members]
## Coroutine utilities                           [exec.coro_utils]
### `execution::as_awaitable`                    [exec.as_awaitable]
### `execution::with_awaitable_senders`          [exec.with_awaitable_senders]
```

Please let me know if we need more changes.

**Comment by ericniebler** [comment]
Merge conflicts. Could you have a look please?

**Pull request merged**
