### PR TITLE
change nest() to delay taking a hold on the async_scope until start

### PR DESCRIPTION
**Pull request by kirkshoop**
change nest() to return a sender that delays taking a hold on the async_scope until start()

### CODE REVIEW

**Comment by LeeHowes** [comment]
Am I correct that in this design it's UB to call `start()` on the result of nest if the scope has gone away?

**Comment by kirkshoop** [comment]
> Am I correct that in this design it's UB to call `start()` on the result of nest if the scope has gone away?

Yes. Just like calls to spawn.. calls to nest()->connect()->start() must occur while the async_scope object is alive.

**Comment by LeeHowes** [comment]
Yes, but `connect()`/`start()` is tightly coupled in library code for the most part. `nest()` is more likely to be used by the user. So it's a reference capturing operation that hides the reference capture. I liked the option to `terminate`. The silent reference capture bothers me more. Hopefully ASAN would catch errors consistently.

**Comment by ericniebler** [comment]
C++ has this problem in spades, and this is nothing new. Just consider iterators. I don't think the possibility of a dangling sender is a problem.

**Pull request merged**
